name: "Run specs"

on:
    - push
    - pull_request

jobs:
    run-specs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'

            - name: Run specs
              run: ./bin/run-parser-specs "php -l"
